language: go
sudo: false

matrix:
  include:
    - go: "1.13.x"
      script: go test -v ./...
    - go: "1.13.x"
      script: go test -v -mod=vendor ./...

go_import_path: willnorris.com/go/imageproxy

env:
  - GO111MODULE=on

install: true
