language: go
sudo: false

matrix:
  include:
    - go: "1.13.x"
      script: go test -v ./...
    - go: "1.13.x"
      script: go test -v -mod=vendor ./...

go_import_path: willnorris.com/go/imageproxy

env:
  - GO111MODULE=on
  - DD_AGENT_HOST=localhost
  - DD_TRACE_AGENT_PORT=8126
  - DD_SERVICE_NAME=safeimage

install: true
