name: images-resizer
namespace: buffer
chart: "buffercharts/buffer-service"
chartVersion: "1.0.2"
cdEnabled: true
cdBranchEnabled: false
dockerfile: Dockerfile
channel: svc-images
clusterName: "kubeeast"
track: stable
replicaCount: 20
uniqueDevRelease: false

image:
  repository: bufferapp/buffer-images-proxy # Override with the docker image
  tag: latest # this will be overriden by the build process
  pullPolicy: IfNotPresent
extraMainContainerValues: {}
resources:
  limits:
    cpu: 400m
    memory: 1400Mi
  requests:
    cpu: 250m
    memory: 500Mi
extraSpecSpecs: {}
env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        key: aws-access-key-id
        name: images-aws
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        key: aws-secret-access-key
        name: images-aws
healthcheck: # checkout https://github.com/bufferapp/EKG for complete docs
  enabled: false
service:
  enabled: false
ingress:
  enabled: false
