name: safeimage
namespace: buffer
deploymentUrl: "safeimage.buffer.com"
chart: "buffercharts/buffer-service"
chartVersion: "1.0.2"
cdEnabled: true
cdBranchEnabled: false
dockerfile: Dockerfile
channel: svc-images
clusterName: "kubeeast"
track: stable
replicaCount: 10

image:
  repository: bufferapp/safeimage # Override with the docker image
  tag: latest # this will be overriden by the build process
  pullPolicy: IfNotPresent
extraMainContainerValues:
  readinessProbe:
    httpGet:
      path: /health-check
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 2
    timeoutSeconds: 1
resources:
  requests:
    memory: 300M
    cpu: 100m
  limits:
    memory: 1G
    cpu: 400m
extraSpecSpecs: {}
healthcheck: # checkout https://github.com/bufferapp/EKG for complete docs
  enabled: false
service:
  enabled: true
  externalPort: 80
  externalTLSPort: 443
  internalPort: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:980620087509:certificate/6b704a93-67de-444c-89fc-9f659bf2dd42
ingress:
  enabled: false
