name: safeimage
namespace: buffer
deploymentUrl: "safeimage.buffer.com"
chart: "buffercharts/buffer-service"
chartVersion: "1.2.2"
cdEnabled: true
cdBranchEnabled: true
dockerfile: Dockerfile
channel: svc-images
clusterName: "kubeeast"
track: stable
latencySensitive: true
replicaCount: 10

image:
  repository: bufferapp/safeimage # Override with the docker image
  tag: latest # this will be overriden by the build process
  pullPolicy: IfNotPresent
extraMainContainerValues:
  readinessProbe:
    httpGet:
      path: /health-check
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 2
    timeoutSeconds: 1
resources:
  requests:
    memory: 300M
    cpu: 100m
  limits:
    memory: 1G
extraSpecSpecs: {}
healthcheck: # checkout https://github.com/bufferapp/EKG for complete docs
  enabled: false
env:
  - name: DD_AGENT_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: DD_TRACE_AGENT_PORT
    value: "8126"
  - name: DD_SERVICE_NAME
    value: "safeimage"
  - name: APM_ENV
    value: "production"

service:
  enabled: true
  externalPort: 80
  externalTLSPort: 443
  internalPort: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:980620087509:certificate/6b704a93-67de-444c-89fc-9f659bf2dd42
ingress:
  enabled: false
